### ISSUE TITLE
Fix branch protection workflow

### ISSUE THREAD

**Issue by vivalareda** [ai-cfia/devops#19]
The script [branch-protection-ruleset.sh](https://github.com/ai-cfia/devops/blob/main/github-management-script/branch-protection-ruleset.sh) currently adds "Python package / build" which is not a test we have it should be "lint-test / build"

**Comment by rngadam** [comment]
You're using a deprecated parameters:

https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28

![image](https://github.com/ai-cfia/devops/assets/538542/e4ff772d-5594-4803-8e58-3e8d3c200d84)

Also, if you're going to add this protection to all branches, you cannot make it specific to the Python check  as we have non-Python repos to; probably the check needs to expose a generic check name ("lint-test" from Python or React) representing the intent of the check rather than its specific language implementation.

Also note that these "infrastructure configuration" are better done through terraform:

https://registry.terraform.io/providers/integrations/github/latest/docs/resources/branch_protection
